### ISSUE TITLE
Issue with "popup window" extension

### ISSUE THREAD

**Issue by uahim** [KSnakeW/Firefox-userChrome.css-style-with-status-panel#2]
many thanks for your work, works like a charm for the standard window!

maybe you have an idea how to hide the status bar when using this addon, too?
https://addons.mozilla.org/en-US/firefox/addon/popup-window/
it pretty much does what it says, it opens the current tab in a new bare window without any ui elements

**Comment by KSnakeW** [comment]
Hi, 
Thank You for words of appreciation.

I have no idea I tested this enough but seems like I resolved Your request.
There is newer version uploaded. Remove comment from line 15 and 19 for get functionality that You asked for... I hope.

Or just paste this into userChrome.css that You using:



```
/* try to hide status panel in pop-up windows */
html[chromehidden~="location"] .browserContainer, #main-window { 
  border-bottom: inherit !important;    
}
```

**Comment by uahim** [comment]
thank you so much for your time, the additional css works fine!

your work re-adds crucial functionality to firefox. thanks again.

**Comment by KSnakeW** [comment]
Thanks! I am beginner so that means much for me that You appreciate my work. I am glad I could help.
