### ISSUE TITLE
Great work! Some small edits...

### ISSUE THREAD

**Issue by ablazhov** [KSnakeW/Firefox-userChrome.css-style-with-status-panel#3]
Finaly a working statusbar solution! Thank you!
I had to tweak the code a bit to accommodate it to work with Fx 128 and to eliminate some functional discrepancies. Also changed some colors to fit it to my current visual theme, but this is not important.
May I present you my edition of your code:

/* Adds bottom space to browser window for status panel */
.browserContainer {  
  padding-bottom: 22px !important;
}

/* Hides permanent status panel when browser is in full screen */
html[inFullscreen="true"] .browserContainer {  
  padding-bottom: 0px !important;
}

/* Uncomment this section to hide status panel in pop-up windows when mouse is not over a link */
/*
:root[chromehidden~="toolbar"] .browserContainer { 
  padding-bottom: 0px !important;    
}
:root[chromehidden~="toolbar"] #statuspanel {
  bottom: 0px !important;
}
:root[chromehidden~="toolbar"] #statuspanel[type="defaultStatus"] {
  visibility: hidden !important;
  opacity: 0 !important;  
}
*/

/* Status panel position and etc. */
#statuspanel {
  height: 22px !important;
  width: 100% !important;
  max-width: 100% !important;
  left: 0px !important;
  bottom: -22px !important;
  padding: 0px !important;
  transition-duration: 150ms !important;
  transition-delay: 50ms !important;
  border-top: 1px solid #909090 !important;
  background-color: #DDDDDD !important;
  box-shadow: 0px -2px 5px rgba(0, 0, 0, 0.20) !important;
}

/* Force status panel to show always, even when empty */
#statuspanel[hidden="true"] {
  position: absolute !important;
  display: block !important;
}
#statuspanel[inactive] {
  visibility: visible !important;
  opacity: 100 !important;
}

/* Temporary status panel position when in full screen mode and mouse is over link*/
html[inFullscreen="true"] #statuspanel {
  bottom: 0px !important;
}
html[inFullscreen="true"] #statuspanel[type="defaultStatus"] {
  visibility: hidden !important;
  opacity: 0 !important;  
}

/* Defines status label parameters to fit it on panel */
#statuspanel-label {
  top: 0px !important;
  margin-left: 0px !important;
  margin-top: 2px !important;
  border: none !important;
  padding-left: 5px !important;
  padding-top: 0px !important;
  background: transparent !important;
  transition-duration: 150ms !important;
  transition-delay: 50ms !important;
  color: black !important;
  text-shadow: 1px 1px #f3f3f3 !important;
}

/* Hides label text when there is no any action with browser or website i.ex. mouse not hovering any link */
#statuspanel[type="defaultStatus"] #statuspanel-label {
  visibility: hidden !important;
  opacity: 0 !important;  
}

/* Prevents status panel to cover search bar */
findbar {
  margin-top: 22px !important;
  border-top: 1px solid #979898 !important;
}
.browserContainer > findbar {
  margin-bottom: -22px !important;
}

/* Prevents status panel to cover developer tools when they are on bottom */
splitter.devtools-horizontal-splitter {
  margin-top: 20px !important;
}
.devtools-toolbox-bottom-iframe {
  margin-bottom: -22px !important;
  border-top: 1px solid #979898 !important;
}

**Comment by KSnakeW** [comment]
Great work! I incorporated some of your ideas into the newest version, if you don't mind, of course. For others, I need more time to check if there is a reason to change them, because I want everything to work on any OS and any modification should be as small as possible.

And... I really didn't notice that some parts of the mod stopped working since version 128.

**Comment by ablazhov** [comment]
> I incorporated some of your ideas into the newest version, if you don't mind, of course.

By all means!
